In [1]:
from sklearn import preprocessing 
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import numpy as np

In [2]:
from sklearn.preprocessing import LabelEncoder

In [26]:
data=pd.read_csv('play_tennis.csv.xls')
data_train=pd.read_csv('play_tennis.csv.xls')
data_test=pd.read_csv('play_tennis.csv.xls')

In [27]:
data.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [29]:
le=LabelEncoder()

In [41]:
objlist=['day','outlook','temp','humidity','wind']


In [42]:
for feat in objlist:
    data[feat]=le.fit_transform(data[feat].astype(str))

In [43]:
y=le.fit_transform(data['play'].astype(str))

In [44]:
X=data.iloc[:,:-1]

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=4)

In [52]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [53]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [63]:
X_train,X_test

(array([[4.8, 3.4, 1.6, 0.2],
        [5.7, 2.5, 5. , 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [4.8, 3. , 1.4, 0.1],
        [4.7, 3.2, 1.3, 0.2],
        [6.5, 3. , 5.8, 2.2],
        [4.6, 3.4, 1.4, 0.3],
        [6.1, 3. , 4.9, 1.8],
        [6.5, 3.2, 5.1, 2. ],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 2.8, 4.5, 1.3],
        [6.7, 3.3, 5.7, 2.5],
        [6. , 3. , 4.8, 1.8],
        [5.1, 3.8, 1.6, 0.2],
        [6. , 2.2, 4. , 1. ],
        [6.4, 2.9, 4.3, 1.3],
        [6.5, 3. , 5.5, 1.8],
        [5. , 2.3, 3.3, 1. ],
        [6.3, 3.3, 6. , 2.5],
        [5.5, 2.5, 4. , 1.3],
        [5.4, 3.7, 1.5, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5.2, 4.1, 1.5, 0.1],
        [6.7, 3.3, 5.7, 2.1],
        [4.4, 3. , 1.3, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [5.9, 3. , 5.1, 1.8],
        [5.2, 3.5, 1.5, 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [5.8, 2.7, 4.1, 1. ],
        [4.9, 3.1, 1.5, 0.1],
        [7.4, 2.8, 6.1, 1.9],
        [6

In [56]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 1])

In [57]:
y_test

array([1, 1, 1, 1, 1, 0])

In [58]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [59]:
y_pred=classifier.predict(X_test)
print(y_test)

[1 1 1 1 1 0]


In [60]:
from sklearn import metrics

In [61]:
accuracy_score=metrics.accuracy_score(y_test,y_pred)
print("The accuracy is",accuracy_score)

The accuracy is 0.8333333333333334
